.travis.yml
dreal/symbolic/BUILD
dreal/symbolic/symbolic.h
dreal/symbolic/test/symbolic_test.cc

Mainly to test PR workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/11)

Add more symbolic test

---

dreal/symbolic/symbolic.cc
dreal/symbolic/symbolic.h
dreal/symbolic/test/symbolic_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/20)

feat(symbolic): Add CreateVector

---

.gitignore
.travis.yml
BUILD
README.md
dreal/BUILD
dreal/__init__.py
dreal/api/BUILD
dreal/api/__init__.py
dreal/api/api_py.cc
dreal/api/test/api_test.cc
dreal/api/test/api_test.py
dreal/symbolic/BUILD
dreal/symbolic/__init__.py
dreal/symbolic/symbolic_py.cc
dreal/symbolic/test/symbolic_test.py
dreal/util/BUILD
dreal/util/__init__.py
dreal/util/test/util_test.py
dreal/util/util_py.cc
dreal/workspace.bzl
tools/BUILD
tools/CROSSTOOL
tools/bazel.rc
tools/dreal.bzl
tools/pybind11.BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/66)

bazel: Add pybind11 and a small test

---

dreal/smt2/driver.cc
dreal/solver/context.cc
dreal/solver/context.h
dreal/solver/context_impl.cc
dreal/solver/context_impl.h

Fix #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/77)

DeclareLocalVariable declare non-model variables

---

dreal/smt2/driver.cc
dreal/solver/context.cc
dreal/solver/context.h
dreal/solver/context_impl.cc
dreal/solver/context_impl.h

+@martinjos for feature-review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/78)

DeclareLocalVariable declares non-model variables

---

third_party/com_github_robotlocomotion_drake/tools/workspace/pkg_config.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/103)

bazel(pkg_config.bzl): Include copts

---

BUILD.bazel
WORKSPACE
dreal/BUILD.bazel
dreal/api/BUILD.bazel
dreal/solver/BUILD.bazel
dreal/symbolic/BUILD.bazel
dreal/symbolic/prefix_printer.cc
dreal/symbolic/prefix_printer.h
dreal/symbolic/symbolic_py.cc
dreal/symbolic/test/prefix_printer_test.cc
dreal/symbolic/test/symbolic_test.py
dreal/util/BUILD.bazel
setup/ubuntu/14.04/install_prereqs.sh
setup/ubuntu/16.04/install_prereqs.sh
setup/ubuntu/18.04/install_prereqs.sh
tools/dreal.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/106)

Add PrefixPrinter and ToPrefix

---

dreal/dreal_py.cc
dreal/smt2/driver.cc
dreal/smt2/sort.cc
dreal/smt2/sort.h
dreal/test/python/symbolic_test.py

I went through the building and testing steps in `CONTRIBUTING.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/115)

Expose Binary type in smt2 driver and python API

---

.bazelrc
dreal/dr/BUILD.bazel
dreal/dr/parser.yy
dreal/smt2/BUILD.bazel
dreal/smt2/parser.yy
dreal/workspace.bzl
third_party/com_github_google_kythe/tools/build_rules/BUILD.bazel
third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl
third_party/com_github_westes_flex/BUILD.bazel
third_party/com_github_westes_flex/COPYING
third_party/com_github_westes_flex/FlexLexer.h
third_party/com_github_westes_flex/README.md

Close https://github.com/dreal/dreal4/issues/127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/128)

feat: Use homebrew flex/bison on mac

---

.bazelrc
tools/dreal.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/162)

bazel: Remove --incompatible_remove_legacy_whole_archive=false

---

dreal/workspace.bzl
setup/ubuntu/16.04/install_prereqs.sh
setup/ubuntu/18.04/install_prereqs.sh
tools/fmt.BUILD.bazel
tools/spdlog.BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/164)

Update fmt / spdlog / bazel

---

dreal/dr/parser.yy
dreal/smt2/parser.yy

Close #127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/179)

fix(dr,smt2): Add %destructor in yy

---

dreal/dr/parser.yy
dreal/dr/scanner.ll
dreal/smt2/parser.yy
dreal/smt2/scanner.ll
dreal/smt2/term.cc
dreal/smt2/term.h
setup/ubuntu/16.04/install_prereqs.sh
setup/ubuntu/18.04/install_prereqs.sh
setup/ubuntu/20.04/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/213)

Refactor smt2/dr parsers

---

dreal/BUILD.bazel
dreal/smt2/logic.cc
dreal/smt2/logic.h
dreal/test/python/BUILD.bazel
dreal/test/smt2/BUILD.bazel
dreal/test/smt2/set_logic_all.smt2
dreal/test/smt2/set_logic_all.smt2.expected

Support (set-logic ALL)

---

dreal/dreal_main.cc
dreal/smt2/driver.cc
dreal/solver/config.cc
dreal/solver/config.h
dreal/solver/context_impl.cc
dreal/test/smt2/BUILD.bazel
dreal/test/smt2/option_smt2_compliant_01.smt2
dreal/test/smt2/option_smt2_compliant_01.smt2.expected
dreal/test/smt2/option_smt2_compliant_02.smt2
dreal/test/smt2/option_smt2_compliant_02.smt2.expected

feat(smt2): Add --smt2-compliant option

---

docs/BuildOnFedora.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/227)

docs: Add BuildOnFedora.md

---

.travis.yml

- unshallow homebrew-{core,cask}
- remove python2-numpy hack

travis: Update macOS

---

dreal/symbolic/prefix_printer.cc
dreal/symbolic/test/prefix_printer_test.cc

Close #275
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/277)

fix(symbolic/prefix_printer): Handle negative constants

---

dreal/smt2/logic.cc
dreal/smt2/logic.h

Close #274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/276)

Add missing logic

---

dreal/optimization/BUILD.bazel
dreal/optimization/cached_expression.cc
dreal/optimization/cached_expression.h
dreal/optimization/nlopt_optimizer.cc
dreal/optimization/nlopt_optimizer.h

Previously, it was part of nlopt_optimizer.h. Now it is in a separate file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/290)

refactor(optimization/cached_expression): CachedExpression

---

test/BUILD.bazel
test/cds_priority_queue_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/289)

test: Add cds_priority_queue_test

---

WORKSPACE

See https://github.com/dreal-deps/ezoptionparser/commit/5bb9214fc26bf14cea071411216e23799cabd0da .
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/291)

bazel(WORKSPACE): Update ezoptionparser

---

dreal/dr/BUILD.bazel
dreal/smt2/BUILD.bazel
dreal/workspace.bzl
third_party/com_github_robotlocomotion_drake/dreal/symbolic/test/symbolic_variable_test.cc
tools/picosat.BUILD.bazel

@yazhai , I've checked that it works with the existing set of the supported compilers in Github Action (<= clang-14). Can you check if it works with clang-15 locally?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/292)

Fixes to support clang-15

---

.github/workflows/check_install.yml
.github/workflows/docker.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
tools/dreal.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/293)

fix(tools): Update dreal.bzl to be compatible with bazel-6 on macos

---

.github/workflows/ubuntu.yml
BUILD.bazel
README.md
WORKSPACE
dreal/contractor/BUILD.bazel
dreal/contractor/contractor.h
dreal/contractor/contractor_ibex_fwdbwd.h
dreal/contractor/contractor_ibex_polytope.h
dreal/dreal_py.cc
dreal/solver/BUILD.bazel
dreal/solver/theory_solver.h
dreal/test/python/BUILD.bazel
dreal/test/python/contractor_test.py
tools/dreal.bzl

- ContractorStatus
- Contractor
- DynamicBitset
- BuildContractor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/294)

Add more to Python binding

---

.github/workflows/check_install.yml
.github/workflows/docker.yml
.github/workflows/ubuntu.yml
README.md
notebooks/dreal4-python3.ipynb
scripts/update_dreal_version.sh
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/298)

Retire Ubuntu-18.04

---

.github/workflows/macos.yml
README.md
notebooks/dreal4-python3.ipynb
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dreal/dreal4/301)

Retire macOS-10 / update Google Colab notebook
